### ISSUE TITLE
i have an error when call from postman

### ISSUE THREAD

**Issue by ehsanshrz** [Hossein-s/nesjts-todo-article#3]
i have this error:```
 {
    "statusCode": 500,
    "message": "Internal server error"
}
```
when call http://127.0.0.1:3000/todo
with this body:```
 {
	"text": "learn nestjs",
	"completed": false
}
```
and also get this to terminal:
```
SQLITE_CONSTRAINT: NOT NULL constraint failed: todo.completeTime +41142ms
QueryFailedError: SQLITE_CONSTRAINT: NOT NULL constraint failed: todo.completeTime
    at new QueryFailedError (D:\nest\todo-app\node_modules\typeorm\error\QueryFailedError.js:11:28)
    at Statement.handler (D:\nest\todo-app\node_modules\typeorm\driver\sqlite\SqliteQueryRunner.js:48:38)
```

**Comment by Hossein-s** [comment]
از خطا معلومه که فیلد completeTime دارای خصوصیت nullable: true نیست.

توی کدهای گیت‌هاب درسته ولی توی مقاله دیدم که درست نیست.. از اینجا نگاه کنید.

https://github.com/Hossein-s/nesjts-todo-article/blob/fd0117ff427475176512094496fe48dacae7e2db/src/todo/todo.entity.ts#L18
